# Copyright 2020 IOTA Stiftung
# SPDX-License-Identifier: Apache-2.0

[package]
name = "wasmclient"
description = "Smart Contract interface library for Wasm clients"
license = "Apache-2.0"
version = "1.0.21"
authors = ["Eric Hop <eric@iota.org>"]
edition = "2018"
repository = "https://github.com/iotaledger/wasp"

[features]
default = ["console_error_panic_hook"]

[dependencies]
iota-crypto = { git = "https://github.com/iotaledger/crypto.rs", branch = "dev", default-features = false, features = [ "blake2b", "ed25519" ] }
wasmlib = { path = "../wasmlib" }
#wasmlib = { git = "https://github.com/iotaledger/wasp", branch = "develop" }
wasm-bindgen = "0.2.87"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
bech32 = "0.9.1"
base64 = "0.21.4"
reqwest = { version = "0.11.22", features = ["blocking", "json"] }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
url = "2.4.1"
ws = "0.9.2"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.37"
testwasmlib = { path = "../../../contracts/wasm/testwasmlib/rs/testwasmlib" }
