# Copyright 2020 IOTA Stiftung
# SPDX-License-Identifier: Apache-2.0
copyright:

name: HelloWorld
version: 0.1.1
description: The ubiquitous hello world demo

author: Eric Hop <eric@iota.org>
license: Apache-2.0
repository: https://github.com/iotaledger/wasp

events: {}
structs: {}
typedefs: {}

state: {}

funcs:
  helloWorld: {}

views:
  getHelloWorld:
    results:
      helloWorld: String
