# Copyright 2020 IOTA Stiftung
# SPDX-License-Identifier: Apache-2.0
copyright:

name: IncCounter
version: 0.1.1
description: Increment counter tests

author: Eric Hop <eric@iota.org>
license: Apache-2.0
repository: https://github.com/iotaledger/wasp

events:
  counter:
    value: Int64

structs: { }
typedefs: { }

state:
  counter: Int64
  numRepeats: Int64

funcs:
  callIncrement: { }
  callIncrementRecurse5x: { }
  endlessLoop: { }
  increment:
    params:
      counter: Int64? # value to add to counter,default is 1
  incrementWithDelay:
    params:
      delay: Uint32 # delay in seconds
  init:
    params:
      counter: Int64? # value to initialize state counter with
  localStateInternalCall: { }
  localStatePost: { }
  localStateSandboxCall: { }
  postIncrement: { }
  repeatMany:
    params:
      numRepeats: Int64? # number of times to recursively call myself
  testVliCodec: { }
  testVluCodec: { }
  whenMustIncrement:
    params:
      dummy: Int64? # dummy param to prevent 'duplicate outputs not allowed'

views:
  getCounter:
    results:
      counter: Int64
  getVli:
    params:
      ni64: Int64
    results:
      ni64: Int64
      xi64: Int64
      buf: Bytes
      str: String
  getVlu:
    params:
      nu64: Uint64
    results:
      nu64: Uint64
      xu64: Uint64
      buf: Bytes
      str: String
