# Copyright 2020 IOTA Stiftung
# SPDX-License-Identifier: Apache-2.0
copyright:

name: storage
version: 0.1.1
description: Gas calibration storage

author: Larry Ivange <larry.ivange@iota.org>
license: Apache-2.0
repository: https://github.com/iotaledger/wasp

events: {}
structs: {}
typedefs: {}

state:
  v: Uint32[]

funcs:
  f:
    params:
      n: Uint32

views: {}
