# Copyright 2020 IOTA Stiftung
# SPDX-License-Identifier: Apache-2.0
copyright:

name: CoreContracts
version: 0.1.1
description: Tests core contract interfaces

author: Yanghao Yuan <yanghao.yuan@iota.org>
license: Apache-2.0
repository: https://github.com/iotaledger/wasp

events: {}
structs: {}
typedefs: {}
state:
funcs:
views:
