# Copyright 2020 IOTA Stiftung
# SPDX-License-Identifier: Apache-2.0
copyright:

name: CoreErrors
version: 1.0.11
description: Errors Contract

author: Eric Hop <eric@iota.org>
license: Apache-2.0
repository: https://github.com/iotaledger/wasp

structs: {}
typedefs: {}
state: {}
funcs:

  # Registers an error message template.
  # note that this function must be call()ed
  registerError:
    params:
      template=m: String # error message template string
    results:
      errorCode=c: Bytes # serialized error code

views:

  # Returns the message template stored for a given error code.
  getErrorMessageFormat:
    params:
      errorCode=c: Bytes # serialized error code
    results:
      template=m: String # error message template string
