# Copyright 2020 IOTA Stiftung
# SPDX-License-Identifier: Apache-2.0
copyright:

name: WasmRequests
version: 1.0.11
description: WasmLib request structures

author: Eric Hop <eric@iota.org>
license: Apache-2.0
repository: https://github.com/iotaledger/wasp

events: {}
structs:
  CallRequest:
    contract: Hname
    function: Hname
    params: Bytes
    allowance: Bytes # caller assets that the call is allowed to access

  DeployRequest:
    progHash: Hash
    name: String
    params: Bytes

  PostRequest:
    chainID: ChainID
    contract: Hname
    function: Hname
    params: Bytes
    allowance: Bytes # caller assets that the call is allowed to access
    transfer: Bytes # assets that are transferred into caller account
    delay: Uint32

  SendRequest:
    address: Address
    transfer: Bytes

  TransferRequest:
    agentID: AgentID
    transfer: Bytes

typedefs: {}
state: {}
funcs: {}
views: {}
