# Copyright 2020 IOTA Stiftung
# SPDX-License-Identifier: Apache-2.0
copyright:

name: timestamp
version: 0.1.1
description: Extremely simple timestamp server

author: Eric Hop <eric@iota.org>
license: Apache-2.0
repository: https://github.com/iotaledger/wasp

events: {}
structs: {}
typedefs: {}

state: {}

funcs:
  now: {}

views:
  getTimestamp:
    results:
      timestamp: Uint64 # last official timestamp generated
